### ISSUE TITLE
connection refuse occur when i click ep_draw button

### ISSUE THREAD

**Issue by crestina** [JohnMcLear/ep_draw#18]
did i miss something for prozy settings? 
I only install ep?_draw plugin in my etherpad and added below in setting.jason

   /* EP draw configurations */
   "ep_draw": {
        "host": "localhost:9001",
        "onByDefault": true
    },

**Comment by JohnMcLear** [comment]
Still looks wrong.  Hire a dev to help you

**Comment by c526537207** [comment]
@JohnMcLear I also met the same problem, single in the etherpad ep_draw button, https://localhost:9002/d/fff?AuthorName =Testing&authorColor= RGB (243,%20165,%20231), status failed, no response
