### ISSUE TITLE
Error installing ep_draw with Etherpad 1.6.1

### ISSUE THREAD

**Issue by dbareiro** [JohnMcLear/ep_draw#24]
Hi, John. Thanks for developing this plugin to integrate Etherdraw with Etherpad.

I tried to install it from the console, but I get this error:

```
etherpad@conference:~/etherpad-lite$ npm install ep_draw
/opt/etherpad/etherpad-lite
└── ep_draw@0.0.11 
 
npm WARN enoent ENOENT: no such file or directory, open '/opt/etherpad/etherpad-lite/package.json'
npm WARN etherpad-lite No description
npm WARN etherpad-lite No repository field.
npm WARN etherpad-lite No README data
npm WARN etherpad-lite No license field.
```

Do you know what the problem might be?

I'm using Etherpad 1.6.1.

Thanks in advance.

Kind regards,
Daniel

**Comment by jacq0123** [comment]
We installed both etherdraw and etherpad and had some problems, while each work independently well. I'm interested to the solution to make both work on the same server as well.

**Comment by dbareiro** [comment]
Hello, jacq0123.

> We installed both etherdraw and etherpad and had some problems, while each work
> independently well. I'm interested to the solution to make both work on the same 
> server as well.

The same here. Did you have the same error as the one shown in my previous message when trying to install ep_draw to integrate Etherdraw with Etherpad?

Kind regards,
Daniel

**Comment by jacq0123** [comment]
Let me check with the developer. But, I'm not sure that he installed the ep_draw to integrate both.


________________________________

**Comment by JohnMcLear** [comment]
I just tested this and it's working fine for me, let me know if it's still an issue for you.
