### ISSUE TITLE
iOS doesn't show full 

### ISSUE THREAD

**Issue by JohnMcLear** [JohnMcLear/ep_draw#27]
drawEmbed frame

**Comment by JohnMcLear** [comment]
@Seballot any ideas on this?

**Comment by seballot** [comment]
killing apple one for all? :)

More seriously, I don't understand what you are talking about, could you explain more, and give  screenshot please? Thanks you !!

**Comment by JohnMcLear** [comment]
Doh I thought I included some info via email :)

**Comment by JohnMcLear** [comment]
![image](https://user-images.githubusercontent.com/220864/80921823-9db59c80-8d70-11ea-87be-9c5a00f3f4e5.png)

**Comment by JohnMcLear** [comment]
Ignore the Error.  See the height of the drawing never fills the page where in Windows/Firefox/Chrome et al it's fine.  It was fine pre 1.8 afaik.

**Comment by seballot** [comment]
is it deployed somewhere so I can test? I tried the url we used in saucelabs but no longer works

**Comment by JohnMcLear** [comment]
@seballot did you get onto this?  Afaik I gave you details over email??

**Comment by seballot** [comment]
Nop I think this email get lost somewhere in the internet ! :)

but I guess I jusr need to install etherdraw and ep_draw right?

**Comment by JohnMcLear** [comment]
I sent you an email with details :)

**Comment by seballot** [comment]
Hi ! I just tested with saucelab using safari 12 and safari 13, and it works fine it take full height full width

Does the issue solved itself? :) or is it happening on older safari version?

**Comment by JohnMcLear** [comment]
I also tested and can confirm it seems to have fixed itself? :D
