### ISSUE TITLE
Connect Draw Window to Pad

### ISSUE THREAD

**Issue by packardone** [JohnMcLear/ep_draw#31]
Because the draw window opens with a transparent background, users believe that, if they circle or mark text that is on the pad, all users see that circle or mark in the same place--over the same words on the pad itself.  Since they don't, this leads to confusion.

Could there be a way to connect a mark on the drawing to a specific passage of text, while accounting for all screen sizes?  I suspect that this would be impossible, but I wanted to raise the issue nonetheless.

**Comment by JohnMcLear** [comment]
You would have to deliver the pad content at a fixed size which would be against how Etherpad is built.  The only thing I can suggest is that ep_comments is used to draw attention to a specific piece of content?

**Comment by packardone** [comment]
Understood.  Is there an option, then, to open the draw tool without having the background transparent?  Being transparent suggests that draw can be used to mark the underlying text.

**Comment by JohnMcLear** [comment]
It's not passable at the moment but getParameterByName is only supporting authorColor atm so extending it out and setting the backround to white or something would be easy.  Another option is to just set it as a global setting in settings.json
