### ISSUE TITLE
[100€ Bounty] add an option to automatically start on fullscreen on click

### ISSUE THREAD

**Issue by AliKarpuzoglu** [JohnMcLear/ep_draw#36]
Instead of opening the small preview, and animating to fullscreen on click on the pen/ double click on the icon, it would be great to just open it in full on a single click on the icon.

I already added the options, but I sadly couldn't test it out. Maybe someone can help me out

**Comment by AliKarpuzoglu** [comment]
to be eligible for the bounty, please comment and message me to confirm that no one else is working on it first

**Comment by rs4231199** [comment]
@AliKarpuzoglu Is anyone working on it?

**Comment by AliKarpuzoglu** [comment]
@rs4231199 no one contacted me. So you can go ahead.
Send me an email Ali at alikarpuzoglu com first quickly

**Comment by AliKarpuzoglu** [comment]
Fixed with #40 and #37  

I'll close the issue. We’re in contact via mail for the bounty.

**Comment by rs4231199** [comment]
Thanks @AliKarpuzoglu . 
I have received the bounty for solving this issue.
