### ISSUE TITLE
[100€ Bounty] "Hand" - scrolling does not work on mobile

### ISSUE THREAD

**Issue by AliKarpuzoglu** [JohnMcLear/ep_draw#39]
The function to move the whiteboard content around is not working on touch screens. Tested on Android (9) and iOS  (13.6)

**Comment by AliKarpuzoglu** [comment]
to be eligible for the bounty, please comment and message me to confirm that no one else is working on it first

**Comment by ChaituVR** [comment]
Just for reference to others, i have started working on this

**Comment by ChaituVR** [comment]
Thanks @AliKarpuzoglu i received the bounty for this :)
